#lang sicp

(define (p row col)
  (cond ((> col row) (display "f") #f)
        ((= col 1) 1)
        ((= row col) 1)
        (else (+ (p (dec row) col) (p (dec row) (dec col))))
        )
  )
(p 4 6)

(define (draw n)
  (define (draw-row n)
    (define (draw-row-iter n c)
      (begin
        (display (p n c))
        (display " ")
        (if (= c n) (newline)
            (draw-row-iter n (inc c))
            )
        )
      )
    (draw-row-iter n 1)
    )
  (define (draw-iter n c)
    (if (<= c n)
        (begin (draw-row c)
               (draw-iter n (inc c))))
    )
  (draw-iter n 1)
  )
(draw 10)