#lang sicp
(define (cont-frac n d k)
  (define (step i)
    (if (= i k) (/ (n i) (d i))
        (/ (n i) (+ (d i) (step (+ 1 i))))
        ))
  (step 1))

(define (tan x k)
  (define (n i) (if (= i 1) x (- (* x x))))
  (define (d i) (+ (* 2 (- i 1)) 1))
  (cont-frac n d k)
)
(define (gr k) (tan 1.0 k))
(gr 1)
(gr 2)
(gr 3)
(gr 4)
(gr 5)
(display 5)
(newline)
(gr 6)
(gr 7)
(gr 8)
(gr 9)
(gr 10)

